version: "3"
services:
    megalb-db:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: MegaLeaderboard
    megalb-flyway:
        image: flyway/flyway:latest-alpine
        command: -url=jdbc:postgresql://megalb-db/MegaLeaderboard -schemas=public -user=admin -password=mysecretpassword -connectRetries=60 migrate
        volumes:
            - ./migrations:/flyway/sql
        depends_on:
            - megalb-db